(** Lexical typing environment for static type analysis and Hindley-Milner inference. Maps
    variable identifiers to polytype schemes. Guarantees Law 5 (Determinism). *)

type t
(** Immutable typing environment mapping variable identifiers to type schemes. *)

val empty : t
(** The empty typing environment. *)

val is_empty : t -> bool
(** Returns true if the environment contains no bindings. *)

val extend : string -> Types.scheme -> t -> t
(** Extends the typing environment with a variable binding mapped to a polytype scheme.
    Shadows any prior binding with the same name. *)

val extend_type : string -> Types.t -> t -> t
(** Convenience helper extending the environment with a monomorphic type scheme
    [Forall ([], ty)]. *)

val lookup : string -> t -> Types.scheme option
(** Looks up the type scheme bound to an identifier. *)

val mem : string -> t -> bool
(** Checks whether an identifier is bound in the environment. *)

val remove : string -> t -> t
(** Removes an identifier from the environment. *)

val apply_subst : Types.subst -> t -> t
(** Applies a type substitution across all schemes in the environment. *)

val ftv : t -> Types.IntSet.t
(** Computes the set of free type variables across all schemes in the environment. *)

val max_var : t -> int
(** Computes the maximum type variable identifier present in the environment (or -1 if
    none). Used to seed fresh type variable generation without collisions. *)

val generalize : t -> Types.t -> Types.scheme
(** Generalizes a type with respect to an environment by quantifying over all type
    variables that are free in the type but not free in the environment. *)

val instantiate : (unit -> Types.t) -> Types.scheme -> Types.t
(** Instantiates a polytype scheme by replacing quantified variables with fresh type
    variables generated by the provided generator function. *)

val to_list : t -> (string * Types.scheme) list
(** Returns the environment bindings as an association list. *)

val of_list : (string * Types.scheme) list -> t
(** Constructs an environment from an association list of bindings. *)

val pp : Format.formatter -> t -> unit
(** Pretty-prints the typing environment. *)

val to_string : t -> string
(** Formats the typing environment as a human-readable string. *)
