(test
 (name test_typechecker)
 (modules test_typechecker)
 (libraries vesper alcotest))

(test
 (name test_patterns)
 (modules test_patterns)
 (libraries vesper alcotest))

(test
 (name test_modules)
 (modules test_modules)
 (deps
  (source_tree ../fixtures))
 (libraries vesper alcotest))

(test
 (name test_bytecode_vm)
 (modules test_bytecode_vm)
 (libraries vesper alcotest))

(test
 (name test_stdlib)
 (modules test_stdlib)
 (libraries vesper alcotest))

(test
 (name test_lsp)
 (modules test_lsp)
 (libraries vesper alcotest))

(test
 (name test_cli_repl)
 (modules test_cli_repl)
 (libraries vesper alcotest))
